### ISSUE TITLE
Incorrect Plastic recipe

### ISSUE THREAD

**Issue by NickMartin18** [KirkMcDonald/kirkmcdonald.github.io#100]
Hey man! huge fan of your factorio calculator, only started using it recently but it has definitely made my life easier. While using it, however, I noticed that the calculator doesn't seem to take into account that the plastic recipe actually produces 2 plastic bars per cycle. Basically, the number of refinerys/chemical plants that the calculator says is required to produce 1 belt of plastic produces 2. Thought I would just let you know, thanks again!

**Comment by NickMartin18** [comment]
![plastic_recipe](https://user-images.githubusercontent.com/43263004/45534212-0c22a100-b7c0-11e8-8dad-184d9cc5bcda.PNG)
![20180914014515_1](https://user-images.githubusercontent.com/43263004/45534221-117feb80-b7c0-11e8-8d7f-da80c43183ef.jpg)
![20180914014529_1](https://user-images.githubusercontent.com/43263004/45534228-147adc00-b7c0-11e8-83ec-872d32dd2c6d.jpg)

As you can see, the calculator says that for 1 belt of plastic I need <4 refinery's, and <7 total chemical plants. When tested, this actually produces 2 full belts of plastic

**Comment by KirkMcDonald** [comment]
No. The plastic recipe is correct. At a guess, did you enter the wrong number for the beacons? It wants the number of modules, not the number of beacons (as described in the tooltip and the FAQ). Entering half of the desired value would cause it to report a much lower rate of production, as you have observed.

**Comment by NickMartin18** [comment]
Ah, I guess I missed that. Thank you anyways!
