### ISSUE TITLE
Suggestion: Add an easy way to see how much resources a recipe takes.

### ISSUE THREAD

**Issue by L0laapk3** [KirkMcDonald/kirkmcdonald.github.io#103]
Currently The only way to see how many resources manufacturing 1 item takes, is either by copying it to a new tab, or using the visual mode. It would be nice to see exactly how many of my green circuits are required to the red circuit production. Maybe a nice way would be to click on a listitem to unfold it?

Example: I have a calculator that shows whats required for 1.2kspm.  I would like to build the advanced circuit facility. I have created a little mspaint mockup to demonstrate the idea:
![image](https://user-images.githubusercontent.com/6313423/46494406-0c3c1c80-c813-11e8-8ad8-caf263377db0.png)

**Comment by KirkMcDonald** [comment]
This is substantially the same as #54, and is something I've been mulling over for a while. My current thought is to add a tree view as a new tab. (Or, really, to bring back something like the old "items" tab, which I removed ages ago for various reasons.)

I like the mockup here, but I'm closing the issue as a duplicate.
