### ISSUE TITLE
Disabling sulfuric acid from batteries doesn't hide oil refining

### ISSUE THREAD

**Issue by bmick** [KirkMcDonald/kirkmcdonald.github.io#109]
Disabiling sulfuric acid should close the entire recipe tree behind sulfuric acid, which should hide all oil production.  Instead I get a disconnected graph. 
![image](https://user-images.githubusercontent.com/7984983/47325429-885aa080-d618-11e8-987b-d615e9db017d.png)

**Comment by bmick** [comment]
![image](https://user-images.githubusercontent.com/7984983/47325439-91e40880-d618-11e8-99fd-33481ae1a50a.png)

**Comment by KirkMcDonald** [comment]
I can't reproduce this from a fresh page. Do you have a URL which reproduces this?

**Comment by KirkMcDonald** [comment]
Absent a reproducing case, I am closing this issue.
