### ISSUE TITLE
Rocket silo count is incorrect?

### ISSUE THREAD

**Issue by DRY411S** [KirkMcDonald/kirkmcdonald.github.io#123]
When asking the calculator to tell me what I need for all the sciences including space science at 1K per minute, it tells me I need more than 1 silo. Do I really? Can't I just put speed beacons around a single silo?

**Comment by adrianvanderwal** [comment]
Even if you have as many speed beacons around the silo as you can fit, the animation time takes too long for a single silo to sustain 1K SPM.

**Comment by KirkMcDonald** [comment]
This is correct. The calculator models the launch animation time, which limits the rate at which a single silo can launch rockets, regardless of how large of a speed effect you can apply. [The code for this is here.](https://github.com/KirkMcDonald/kirkmcdonald.github.io/blob/master/factory.js#L270)

**Comment by DRY411S** [comment]
Does the 2475 in the code relate to ticks? 41 and a bit seconds?

**Comment by KirkMcDonald** [comment]
As described on the wiki page, the launch animation takes 2475 ticks. The calculator converts this into a number of seconds with the rational 2475/60 (which gets reduced to 165/4), which equals 41.25 seconds.

**Comment by jthill** [comment]
As of 18.18 (not sure exactly when it changed) the launch animation takes 2420 ticks, and one silo can sustain 983 science per minute.
