### ISSUE TITLE
Radar power usage, included in total when they are ingredients

### ISSUE THREAD

**Issue by adrianvanderwal** [KirkMcDonald/kirkmcdonald.github.io#125]
![image](https://user-images.githubusercontent.com/6479661/53015053-07f06300-3485-11e9-9450-750baa19be72.png)

Minor bug.
As the title states, the radars produced include a power usage value, when they are clearly not placed and consume power, but rather are ingredients in another product.

Edit:
https://kirkmcdonald.github.io/calc.html#zip=LY1LCsMwDERv05UN7jaQwxhlmoo4ctCH0NtXlK7E6M2HHaetdnVCNWJI3hTHosuztfbgXaZi1UkHPIl6GfOuG8TYP9VcgzwUxebomgbBKJ0ozhjdpxbWKXVHsvuNZFdWwYxlryHsBQPk6WGqxEqRr1/kyjjKf/cVGF8=

**Comment by KirkMcDonald** [comment]
This is not a bug. That value is the power consumption of the assembling machine making the radar.
