### ISSUE TITLE
Tool is not counting power of beacons themselves

### ISSUE THREAD

**Issue by Zaflis** [KirkMcDonald/kirkmcdonald.github.io#126]
Says example of 10000 speed beacons vs 1000 speed beacons:
https://kirkmcdonald.github.io/calc.html#min=3&items=iron-plate:r:2000&modules=iron-plate:p3:p3;s3:10000
They both use same power. Beacons actually drain 480kW per tick.

**Comment by Zaflis** [comment]
I might be wrong afterall. Seems more reliable testing while setting number of factories constant. Beacons do effect the power i guess.

**Comment by Zaflis** [comment]
I cannot explain this though. What is happening?
https://kirkmcdonald.github.io/calc.html#zip=VchBCsQgDEDR22Q1gh13lhymHVMQogmJwhx/sJuhm8/ntdoxwTWJ0YVrCWvhJB5IXzVyD8OO7io2wmJoalIwRSgNNUE50Vc/+IY6qDlWkx6Uj0H5yhs0KZPpwTulvMX4ukmMcp/M/+z3xR8=

**Comment by Zaflis** [comment]
I see, you don't have math that would count how many beacons there are in total, so you cannot know how much power they would use.
We can assume rows of beacons and that factories are placed tightly, but this would need to be optional setting.
If there are more than 5 beacons per machine it means there's a row on other side too, but 9 or more would require a separation. 9 is an odd case anyway, 10 and 12 are propably the max. But all these form a clear pattern for a math formula when thought through.

**Comment by KirkMcDonald** [comment]
I have previously discussed this issue in #50. I do not plan on including these estimates in the main "factory" tab, as they are strongly dependent on the physical layout of the factory. Any such guess about the total number of beacons will almost certainly be wrong. But I may provide some sort of best-guess when I add this hypothetical "power" tab.

For now, I am closing this issue. To the extent that I plan on addressing this feature, my plan is for it to be part of the feature discussed in #50.
