### ISSUE TITLE
Belt Speeds

### ISSUE THREAD

**Issue by SneakyWyzrd** [KirkMcDonald/kirkmcdonald.github.io#129]
.17 changed the speed of belts. 

Yellow was 13.33/s now 15/s, Red was 26.67/s now 30/s, and Blue was 40/s now 45/s.

Thanks for making this tool it has saved my sanity so many times. Keep up the good work.

**Comment by siorai** [comment]
@SneakyWyzrd so I thought the same thing at first too, but it's because the default settings still point to 0.16 recipes, if you look in the settings you can switch to 0.17, which will show the new belt speeds.

**Comment by SneakyWyzrd** [comment]
I thought I had already switched that over. thanks for pointing that out. Maybe set .17 to the default since most people will be switching over.

**Comment by adrianvanderwal** [comment]
>Maybe set .17 to the default since most people will be switching over.

@KirkMcDonald Is there a way to perhaps store the preferred version for people?
So those that are using the 0.17 (or any other) set won't have to manually change it every time they use the tool?

**Comment by KirkMcDonald** [comment]
0.16 will remain the default so long as that is the stable version. Allowing people to store their preferred default settings is issue #59. As a workaround, I recommend bookmarking the URL with your preferred settings.
