### ISSUE TITLE
Space Science Calculation

### ISSUE THREAD

**Issue by MIZTigerForLife** [KirkMcDonald/kirkmcdonald.github.io#132]
Using the latest published version, space science doesn't have a recipe so none of the calculations work. This happens for any of the recipe sets. 

Unless I'm mis-remembering, space science used to work.

**Comment by KirkMcDonald** [comment]
This is one of those things where I'm not even sure how long it's been broken for. In any case, fixed in 4c9e58a9a31f3f90241c462ecab4baaa09db10fd.
