### ISSUE TITLE
Chemical science pack (3) wrong recipe

### ISSUE THREAD

**Issue by hrompik** [KirkMcDonald/kirkmcdonald.github.io#133]
0.17.0:
Changed name to "Chemical science pack".
Recipe changed to 3 Advanced circuits + 2 Engine units + 1 Solid fuel → 2 Chemical science pack. (Previously 1 Advanced circuit + 1 Engine unit + 1 Electric mining drill → 1 Science pack 3).

https://wiki.factorio.com/Chemical_science_pack

**Comment by hhrhhr** [comment]
https://kirkmcdonald.github.io/calc.html#data=0-17-1&items=chemical-science-pack:f:1

![chem](https://user-images.githubusercontent.com/966048/53795748-ad0a4180-3f43-11e9-9545-829d7c18e52b.png)

Whats wrong?

**Comment by hrompik** [comment]
Oh, settings in url set all time old version of factorio (
