### ISSUE TITLE
Suggestion: allow manual input of intermediate factory numbers

### ISSUE THREAD

**Issue by SteveS8** [KirkMcDonald/kirkmcdonald.github.io#139]
Let's say I want to know what I need for 1000 SPM. It tells me I need 98.12 red circuit assemblers. It would be neat if it allowed me to manually increase that to let's say 104 and then update the other numbers (copper smelters, plastic refinieries, green circuits) accordingly. That way you could easily account for some overproduction in the chains

If you then change something upstream the recipe tree (like the science) it would be ok if it overwrites that manual input again

**Comment by KirkMcDonald** [comment]
You can easily simulate this by adding another build target at the top for the difference. Given that, this seems too trivial to add as a feature in its own right.
