### ISSUE TITLE
Multi-output intermediate products not calculating correctly

### ISSUE THREAD

**Issue by RyenNelsen** [KirkMcDonald/kirkmcdonald.github.io#150]
I've run into this multiple times using the website: recipes that have intermediate ingredients in the chain that generate multiple products (e.g. copper wire) are not being calculated correctly. An example would be having 1 beacon factory calling for 4.5 copper cable factories. In reality, it would only require 2.25 copper wire factories to maintain the ratio.
[Example Link](https://kirkmcdonald.github.io/calc.html#data=0-17-1&min=4&furnace=steel-furnace&belt=fast-transport-belt&mprod=2&items=beacon:r:5)

**Comment by adrianvanderwal** [comment]
That's because it's also calculating the wire required for green and red
circuits.
Click these items to filter them out.

**Comment by RyenNelsen** [comment]
Whoops! I was completely blind to the thought of the rest of the chain. Thank you!
