### ISSUE TITLE
I don't know if it is an issue... oil calculation

### ISSUE THREAD

**Issue by mtfreitasf** [KirkMcDonald/kirkmcdonald.github.io#152]
Kirk,

I made the following calculation: plastic = 8.118. The results were:
![image](https://user-images.githubusercontent.com/29847190/58990789-29b7f080-87bd-11e9-894b-530cc065a62f.png)

My Excel calculations were close but not equal. The produced volume is equal but not the quantity of factories per process. Is it possible that different assumptions were used?

![image](https://user-images.githubusercontent.com/29847190/58991099-d6926d80-87bd-11e9-9309-1507ceffcca4.png)
![image](https://user-images.githubusercontent.com/29847190/58991136-e3af5c80-87bd-11e9-8d9c-8c51ed54b4a9.png)

Sorry if it is not the place for this comment.

Best regards,

Marcos

**Comment by RustyBlade64** [comment]
I think you are using the 0.16 dataset in the calculator, but 0.17 data in your spreadsheet. Crafting speed of chemical plants has changed from 1.25 to 1.0 and crafting time of the cracking recipes has changed from 3s to 2s.

**Comment by mtfreitasf** [comment]
RustyBlade64,

You are correct. Thank you very much.

Best regards,

Marcos
