### ISSUE TITLE
multiple item per production cycle issue

### ISSUE THREAD

**Issue by Rippy01** [KirkMcDonald/kirkmcdonald.github.io#158]
for item recipes that give 2 or more items per cycle such as science packs the calculator will not go by items produced but by how many cycles have been complete.
EX: military science makes 2 packs per cycle when you set it to 60 items per minute it does the calculations that would give you 120 items per minute instead 
Math: each military pack cycle takes 10s for 2 packs the 60 ipm setting gives 10 factories so each factory goes through 6 cycles making 12 packs each which will give you 120 ipm instead of 12

**Comment by adrianvanderwal** [comment]
Do you have a link where these values are displayed?

I suspect you have forgotten about the assembling machine speed.

**Comment by Rippy01** [comment]
yeah i just got reminded about that i had AM 1 as the default so its my bad
