### ISSUE TITLE
Update Chemical Science for 0.17

### ISSUE THREAD

**Issue by atkinson137** [KirkMcDonald/kirkmcdonald.github.io#168]
Chemical Science now takes Solid Fuel (x1) instead of mining drills as of Factorio v 0.17.58

The calculator needs to be updated.

**Comment by raiguard** [comment]
It was already updated. Go to the Settings tab and change the version to 0.17 using the dropdown at the top.

**Comment by KirkMcDonald** [comment]
Yes, 0.16 is still the default. You can change to 0.17 in the settings. (This report may be further evidence that #136 is a good idea.)
