### ISSUE TITLE
Add .17.60 recipes.

### ISSUE THREAD

**Issue by Nucleus24** [KirkMcDonald/kirkmcdonald.github.io#171]
.17.60 has changed a few recipes . Can you update the calculator for them? More info: https://old.reddit.com/r/factorio/comments/cjsmu8/version_01760/

**Comment by SteveS8** [comment]
Would be nice to have the old recipes too though. The oil change is a bit controversial and some people are staying in 17.59 for now. If only to finish ongoing games without large redesigns

**Comment by RustyBlade64** [comment]
I have created a pull request that updates the recipes to 0.17.60.

@SteveS8 I would argue that the official calculator should not have datasets containing information from outdated experimental releases. You can always use the offline version of the calculator (https://github.com/KirkMcDonald/factorio-tools) to host a local calculator from an old game version if you want to keep using that.

**Comment by KirkMcDonald** [comment]
I am getting my tooling into a state where I can dump the current version, and plan on pushing a 0.17.60 dataset once that is working. I believe the only barrier right now is the image-scaling thing. I have yet to receive a PR from @FoxLBA with a fix for this (cf. #172), so I'll probably hack up something of my own in the meantime.

I probably won't make a 0.17.59 dataset. If the devs decide to revert their changes then so be it, but I plan on tracking the game in its current state.

**Comment by FoxLBA** [comment]
Ok. I will made PR with dadaset end then for scaling fix.

**Comment by KirkMcDonald** [comment]
I have pushed KirkMcDonald/factorio-tools@8c66310f5e024dc5772787682acfd62e66bc0a20, which hacks in a solution for these mipmapped icons.

**Comment by KirkMcDonald** [comment]
Done in b2d92eabedb786fadca71906f79808033bfa4a48.
