### ISSUE TITLE
Acknowledge that 0.18 exists

### ISSUE THREAD

**Issue by DRY411S** [KirkMcDonald/kirkmcdonald.github.io#189]
There have been some questions on official factorio Discord about whether the calculator supports 0.18. It does, because no recipes have changed since 0.17.60, but 0.18 is not offered on the settings drop-downs.

**Comment by ingmarins** [comment]
At the very least it could default to 0.17.60 recipes, rather than having to go to settings and change it manually every time, even if playing stable which uses the same recipes anyway.

**Comment by empirebuilder1** [comment]
Another issue is that 0.18 has changed the item capacity of blue belts (40/sec -> 45/sec), and this makes the belts-needed number inaccurate for blue belt builds. One can calculate the new belt number themselves by dividing the items/min by 2700... but the whole point of this is to not do manual work :)

**Comment by DRY411S** [comment]
That capacity did not change in 0.18. Select 0.17 to get all the 0.18 recipe and and belt capacity settings.

**Comment by sorahn** [comment]
It should probably change to '1.0' now and default to that.

**Comment by DRY411S** [comment]
Indeed. But tthe previous fix I provided hasn't been accepted and merged, so I'm holding off another release.
