### ISSUE TITLE
Visualize not working for local data

### ISSUE THREAD

**Issue by schoos76** [KirkMcDonald/kirkmcdonald.github.io#195]
Hi Kirk,

it seems that i cannot use my local data for visualization of the production graph: it just stays empty, and with "Inspect" of the browser, it's just that: the svg-tag is empty. No debug output with -verbose that would give a hint.

How can I troubleshoot this resp. provide more information to you? 

Other recipe settings work just fine.

Michael

**Comment by hhrhhr** [comment]
this is because of https://github.com/KirkMcDonald/kirkmcdonald.github.io/commit/33743c8ab95dd8ad4bbb8b5b8ee90accf3b5481e

function *renderGraph* in *visualize.js* expects image sizes that are set manually in *settings.js*, but not for the local data.

**Comment by schoos76** [comment]
Thanks .. so the issue is: I need to add the new files to the local settings.
