### ISSUE TITLE
Concrete recipe not updated

### ISSUE THREAD

**Issue by crazykid080** [KirkMcDonald/kirkmcdonald.github.io#202]
New recipe is:
2 iron sticks
5 stone bricks
100 water

**Comment by DRY411S** [comment]
Not in vanilla normal recipe mode it isn't.

**Comment by crazykid080** [comment]
Also found an issue with the wall recipe. It also has 1 iron stick in the recipe. This is in normal mode yes

**Comment by DRY411S** [comment]
Vanilla factorio 1.0 does not use iron sticks in the concrete recipe. The code here (commit https://github.com/KirkMcDonald/kirkmcdonald.github.io/commit/8a669c8708bb5319cef518631434e96ae70c0c1f) is using the correct recipe

![image](https://user-images.githubusercontent.com/19732374/91280811-36888180-e77f-11ea-95f3-b428322d4975.png)

https://kirkmcdonald.github.io/calc.html#data=1-0-0&items=concrete:f:1

**Comment by DRY411S** [comment]
https://wiki.factorio.com/Concrete

**Comment by crazykid080** [comment]
Just checked my settings and bio industries was changing the recipe, my bad
