### ISSUE TITLE
Blue circuits calculating quantity of green circuits per second incorrectly

### ISSUE THREAD

**Issue by adamreiswig** [KirkMcDonald/kirkmcdonald.github.io#206]
The website is saying I need 20 green circuits per blue circuit when I mouse over the icon but the calculation is coming out to 24 instead. 20 blue circuit factories (assembler 2) should need 2 full yellow belts of green circuits (30 per second) but the calculator is telling me it needs 36 green circuits per second. In game, I have a build of 20 assembler 2s for blue circuits and they perfectly consume 2 yellow belts of green circuits. I'm pretty sure the calculator is in error but if I'm misunderstanding something about it, I'd love to be educated.

**Comment by DRY411S** [comment]
You are misunderstanding something. :)

The calculator output includes the green circuit makers needed for the red circuits.

If you tell the calculator to ignore the red circuits, by clicking on the red circuit icon in the output, you will see the green circuit calculation that you expected.

Like so:  https://kirkmcdonald.github.io/calc.html#data=1-0-0&min=2&items=processing-unit:f:20&ignore=advanced-circuit

**Comment by adamreiswig** [comment]
Well, you are correct and now I feel like an idiot for wasting your time. I've been using this tool for a while and I can't believe I missed that. Thanks for the reply!
