### ISSUE TITLE
Feature Request: Minimum number of machines needed for all being whole numbers

### ISSUE THREAD

**Issue by saxbophone** [KirkMcDonald/kirkmcdonald.github.io#219]
The Factorio Wiki gives examples for ideal ratios (where 100% of each machine's output at each stage is in use by the next) for manufacturing many items so that the ratios between all machines are whole numbers.

It would be nice to be able to request for this app that rather than a set number of factories or item throughput, instead the "ideal" whole-numbered ratio is provided in the diagram instead.

**Comment by DRY411S** [comment]
kirkcmandonnald is exact. Just round up.

**Comment by saxbophone** [comment]
I know that feature exists but that's not the same thing as what this issue requests, as rounding up would waste some machine capacity.

**Comment by DRY411S** [comment]
I guess it would waste some machine capacity, but then again, building the minimum number of whole number machines might mean that what those machines output is an over or under supply for the next thing in the Production chain. For example, try and find the minimum whole number of machines for blue chips (including chemical plants for plastic, sulphur, acid, and refineries). It will be a very large number of blue chip machines!

**Comment by saxbophone** [comment]
I don't think you're wrong with your analysis! I did think this would be a bit of a niche request. I think mathematically, it can certainly be done but perhaps the benefit in return is quite small...

**Comment by DRY411S** [comment]
I think Kirk McDonald would need to implement something similar to the 'What  If' analysis tool in Microsoft Excel, and as you say it's a little niche. Personally, I don't see the value.

**Comment by saxbophone** [comment]
I think the value is "making the perfectly efficient factory", which is a little niche

**Comment by DawidZwiewka** [comment]
Once you add productivity modules it's nearly impossible to get whole numbers. For instance 1 green circuit machine requires ~3.12056737588652482270... electric funances producing iron plates :D I'm not talking about advanced products like space sience pack but one of the simpliest recipes :)
The truth is that you can get whole numbers only if you are not using any productive modules in most cases and you will use ton of them in most cases :)

**Comment by saxbophone** [comment]
@DawidZwiewka that is useful insight, thank you
