### ISSUE TITLE
Add alt text to icons for screen reader accessibility for blind users

### ISSUE THREAD

**Issue by ohylli** [KirkMcDonald/kirkmcdonald.github.io#250]
The newly updated version of the factorio calculator is no longer accessible for blind users like myself who use a screen reader. The user interface relies heavyly on icons and currently they do not offer a text alternative for screen readers. This can be added with the alt attrivute of img elements. The old version used these so I hope they could be added to this new version as well. 

And in case you are wondering why a blind person would be even needing an accessible factorio calculator, there is [an accessibility mod](https://github.com/Factorio-Access/FactorioAccess) for the game. It allows blind users like myself to play the game all the way to rocket launch and beyond. I personally relied heavily on the calculator when playing. I am currently running the old accessible version locally but of course it will not be useful with space age.

**Comment by KirkMcDonald** [comment]
Done in 6fa8237.
