### ISSUE TITLE
Support terminal recipes?

### ISSUE THREAD

**Issue by infogulch** [KirkMcDonald/kirkmcdonald.github.io#36]
One of the issues I run into with calculators is that I get lost in a sea of details when I'm trying to work out a new build for a specific piece of the factory. As an oversimplified example, let's say I'm working on a red circuit build:

![image](https://cloud.githubusercontent.com/assets/133882/26764828/1d9c8226-4934-11e7-878b-963c5f380672.png)

The whole oil processing subgraph just outputs a single item: plastic bars. I'd like to have it just stop calculating after plastic bars to simplify the graph and make it easier to comprehend since I'm focusing on red circuits right now. Of course I'll want to back out and look at oil production in detail eventually, but for now all I want to know is that I need to produce plastic bars at a rate of X/min.

What would you think about adding a selectable list of "terminal recipes" that are just assumed to be fulfilled and their details are omitted (besides raw rate) when they are a dependency? And to make it easier to look at those details separately, add a link to a new tab that calculates the terminal recipes as outputs?

I'd like to contribute this myself but I wanted to get your opinion first. Thanks for the awesome tool!

**Comment by KirkMcDonald** [comment]
This is already supported. Click on the plastic bar icon in the "Factories" tab.

I'll see about adding the link to a new window.
