### ISSUE TITLE
Switched to "expensive" recipes and "factories" tab was empty

### ISSUE THREAD

**Issue by doktorstick** [KirkMcDonald/kirkmcdonald.github.io#42]
When I switched to "expensive" recipes, the "factories" tab was empty. Changing tabs and "shift-reloading" didn't seem to fix it, but once I navigated to another website and went "back", it started working and it retained the "expensive" recipe selection.

I'm on the latest Chrome.

**Comment by KirkMcDonald** [comment]
Fixed in 6ba9b7313ce6b4301b2a36f371835cc8de34f79b.
