### ISSUE TITLE
Incorrect copper cable calculation?

### ISSUE THREAD

**Issue by zuzudop** [KirkMcDonald/kirkmcdonald.github.io#43]
https://kirkmcdonald.github.io/calc.html#tab=graph&rate=s&min=2&furnace=steel-furnace&mprod=16&items=high-tech-science-pack:f:7
The number of copper cables is wrong. It equals their copper plates input but should be multiplied by 2.
It's ok in lower branches of graph and in Items tab. Incorrect in Factories tab.

**Comment by KirkMcDonald** [comment]
The number is correct. The number you are seeing is a recipe-rate, that is, it is the rate at which the copper cable *recipe* needs to be *crafted*. The "Items" tab and the edges of the graph refer to the item-rate, which is double the recipe-rate, or more than double if productivity modules are used.
