### ISSUE TITLE
number of factory calculation is off

### ISSUE THREAD

**Issue by werelord** [KirkMcDonald/kirkmcdonald.github.io#44]
Example output from the tool:

https://kirkmcdonald.github.io/calc.html#rate=s&min=3&items=science-pack-1:r:5&modules=science-pack-1:p3:p3:p3:p3;s3:12

Given the following formula, in calculating production per second:

`(Amount per craft / base craft time of item) * machine speed * productivity amount = items per second`

for Sci 1, with 4 prod + 12 beacons (speed) this comes out to:

` (1 / 5) * 8 * 1.4 = 2.24 ips`

to reach 5 sci 1 per second:

`5 / 2.24 = 2.232 factories`

The tool however shows 4.2 factories needed, almost twice as many.. Haven't had a chance to look thru the code to figure out why; or am I missing something??

**Comment by KirkMcDonald** [comment]
The number in the "beacons" column is the number of *modules*, not the number of beacons. Specifying 24 modules yields the number you are expecting.
