### ISSUE TITLE
Suggestion: Accept donations

### ISSUE THREAD

**Issue by MakerBurst** [KirkMcDonald/kirkmcdonald.github.io#55]
I wanted to give you $5 for this awesome tool, but I couldn't find any way to do so. A donate link would be nice. 

P.S. I've used many other factorio calculators in the past, but this was by far the best one, and the only one that really gave me what I wanted. Thank you!

**Comment by KirkMcDonald** [comment]
I have added a link to [my Patreon page](https://www.patreon.com/kirkmcdonald) in e81df4f1a1e0c5f113f393df233ac50d31b674d7.
