### ISSUE TITLE
Bug: Furnace is not correctly loaded from URL

### ISSUE THREAD

**Issue by DarkMatterMatt** [KirkMcDonald/kirkmcdonald.github.io#60]
Reproduce by changing the furnace from electric to steel/stone then reloading webpage. The furnace icon will be a black box (because of line 156). The steel/stone furnace will not be used in any calculations (because of line 145).

**Fix**:
settings.js, line 144
`furnace = settings.furnace` should be `furnace = {name: settings.furnace}`
_or_ (but I prefer the one above)
the two `furnace.names` on lines 145 & 156 could be just `furnace`

**Comment by KirkMcDonald** [comment]
Fixed in 8330172f5f244d9248824a7f586b4c310f95aec8.
