### ISSUE TITLE
Bug: Factory tab doesn't update

### ISSUE THREAD

**Issue by DarkMatterMatt** [KirkMcDonald/kirkmcdonald.github.io#69]
Factory tab doesn't update.

Reproduce:

~~1. Go to https://kirkmcdonald.github.io/calc.html with no hash~~ EDIT: this step doesn't matter, bug can be reproduced from custom settings/build targets.
2. Click "Visualize"
3. Change the build target to iron-plates
4. Click "Factory"
5. See that it isn't updated (it still shows red circuits at the top)

Can only reproduce when changing the build target to:

- iron, copper plates (the only things in this list which aren't raw materials)
- iron, copper, stone ores
- water
- crude oil

**Comment by KirkMcDonald** [comment]
Fixed in dccabee47a031f53590d9b591bf270fd3c4ca8e8.
