### ISSUE TITLE
Beacons still used for calculation when downgrading assembling machine to 1

### ISSUE THREAD

**Issue by jhammersholt** [KirkMcDonald/kirkmcdonald.github.io#72]
There is a slight issue with using beacons

Would it be possible to add the beacons display for assembling machines 1?
Or at least clear the beacon setting if you change from assembling machines 2 or 3 to assembling machines 1 (it still uses the beacons for calculating but you cant see that)

Example:
https://kirkmcdonald.github.io/calc.html#min=2&items=electronic-circuit:f:1&ignore=iron-plate,copper-plate&modules=electronic-circuit:;s3:4

Change the assembling machines to use assembling machines 1 the beacons are still used for calculation although you cant see or change that
https://kirkmcdonald.github.io/calc.html#items=electronic-circuit:f:1&ignore=iron-plate,copper-plate&modules=electronic-circuit:;s3:4

**Comment by KirkMcDonald** [comment]
Fixed in 306ce324a9020a9da0d97941c7497e100fc6c7cb.

Beacons don't affect things that don't support modules. I have made such assemblers ignore any previously-configured beacon effect.

**Comment by jhammersholt** [comment]
Thank you - however assembling machines 1 are affected by beacons as stated on the wiki for beacons https://wiki.factorio.com/Beacon even though they have no module slots

> Only buildings with module slots can benefit from beacon effects (i.e. laser turret doesn't benefit). The only exceptions to this rule are Assembling machine 1s, Burner mining drills (both of which don't accept modules but are affected by beacons), and beacons themselves which don't benefit from the modules inserted in themselves (or other beacons), so their energy cost can't be reduced.
