### ISSUE TITLE
Unresolved issue reagarding beacons and assembling machines 1

### ISSUE THREAD

**Issue by jhammersholt** [KirkMcDonald/kirkmcdonald.github.io#73]
Issue described in #72 is still unresolved

assembling machines 1 are affected by beacons as stated on the wiki for beacons https://wiki.factorio.com/Beacon even though they have no module slots

> Only buildings with module slots can benefit from beacon effects (i.e. laser turret doesn't benefit). The only exceptions to this rule are Assembling machine 1s, Burner mining drills (both of which don't accept modules but are affected by beacons), and beacons themselves which don't benefit from the modules inserted in themselves (or other beacons), so their energy cost can't be reduced.

**Comment by KirkMcDonald** [comment]
Empirical testing shows that the wiki is mistaken, and (in 0.16.36, at least) the assembling machine 1 is not affected by beacons. The calculator's behavior is correct.
