### ISSUE TITLE
"Copy to rest of modules" resets to default module when selecting none

### ISSUE THREAD

**Issue by MeAmAnUsername** [KirkMcDonald/kirkmcdonald.github.io#74]
To reproduce:
1. Select a default module in the settings (I chose productivity 3)
2. go to factory tab
3. Select the empty module for the first module slot in one of the recipes*
4. click on arrow ("Copy to rest of modules")

Expected behaviour: all module slots for that recipe are emptied
Actual behaviour: all module slots (including the first one) are reset to the default module.

*first module slot: the slot before the arrow

**Comment by KirkMcDonald** [comment]
Fixed in c5288686b3b226f0ffb6a170e3383cbd2e862254 (along with several other issues with default modules).
