### ISSUE TITLE
Suggestion: Ability to turn on/off advanced oil processing & kovarex enrichment process

### ISSUE THREAD

**Issue by siwy2411** [KirkMcDonald/kirkmcdonald.github.io#75]
It would be really nice to be able to tell the calculator to omit using advanced oil processing and kovarex enrichment process (and maybe some other technologies as well, but those two are most important, I think) for example with two simple checkboxes. These technologies obviously require throwing some science packs at them, and are often not yet discovered when build some mid-game setups. Right now calculator (almost?) always goes for using those technologies (for example when calculating nuclear reactor cycle), which makes it hard to compute actual number of required drills/centrifuges/factories when you have not yet researched those technologies.

BTW - You have made one hell of a tool!

**Comment by KirkMcDonald** [comment]
Added option to change the oil processing recipe in 1cbf8d9b957d3c9688ad46c6f414bbdc0bbd6068.

**Comment by KirkMcDonald** [comment]
Added option to disable Kovarex processing in e5b74e42958a93da75d563ab66492beea1ff17d8.
