### ISSUE TITLE
Calculator stopped working

### ISSUE THREAD

**Issue by shvfn** [KirkMcDonald/kirkmcdonald.github.io#77]
Hi,

first of all: thanks for the calculator! Very useful for larger bases.

But it stopped working today. I have a bookmark for all science packs (1400 per minute) and "end-tech"-settings that used to work ok, but now the output in the "factory"-tab doesn't show the full list anymore. It only shows two rows for red and green science, but no other resources and no oil. When I create a new list, it doesn't work either... some resources don't show up and the factory table is not updated correctly.

I think the "visualization" is still ok, but I never used that.

Also there is now a column "waste/m", probably for Bob's, but I play vanilla. 

I use the latest Firefox on Linux, cleared the cache, reloaded, but that doesn't help.

The url I used is [this one](https://kirkmcdonald.github.io/calc.html#zip=bcnLCgIxDIXht+nKwtSKi4E8TC9hGpxeSCLo2+ssBhS6OXD+T0OEjcMoplIDbyLuCvgajCJWOTQZndUe2eQKw5scQY5N4O6GFKuAJMKW0I6QHtatvLrbslz+6nVa/Vkr7aSB3/aXTxzc8zMp9TblQluxiqlMVb4HZ/IB).

Thanks!

**Comment by shvfn** [comment]
@viktro78 : That did the trick! Had to switch two times back and forth, but now it works again! Issue closed. Thanks!

**Comment by KirkMcDonald** [comment]
There was a bug here, which was that I had broken certain old URLs. This should be corrected in a74d4603d6501232a80814bcfb2a6e0f0ece3e70.
