### ISSUE TITLE
not displaying factory tab properly

### ISSUE THREAD

**Issue by xenoxaos** [KirkMcDonald/kirkmcdonald.github.io#78]
Looks like there was a recent update and it's not playing properly with chrome (maybe others too)

https://kirkmcdonald.github.io/calc.html#zip=bcnLCsJADIXht5mVAdsiSCEPM02DE+xcSCLo29dCFwqzORz+L0vBMSy8OfK7KZuBayzWqjocOawZ2xTWBe1YwnsQ52xoJFyIoUV6wjjrPNyul7849OJ0xiybeNQP/OppTev6IpdaeprkkcCZUg/t+7kDOw==  

![screenshot from 2018-04-23 01-17-17](https://user-images.githubusercontent.com/543939/39109801-19287296-4694-11e8-8e18-ba4a395e2c69.png)

**Comment by xenoxaos** [comment]
It does appear to be working now. I have a feeling that I caught this between commits that appear to have been pushed not too long ago.

**Comment by KirkMcDonald** [comment]
There was a bug in which I had broken certain old URLs. This should be fixed in a74d4603d6501232a80814bcfb2a6e0f0ece3e70.
