### ISSUE TITLE
Factory tab is not working again.

### ISSUE THREAD

**Issue by viktro78** [KirkMcDonald/kirkmcdonald.github.io#79]
Factory tab is broken, this time switching modes does not fix the issue.

**Comment by Calibretto22** [comment]
I may have a similar problem. 
When adding calculating Productivity-Modules 3 & Speed-Modules 3 the ingredients are not shown. 
When loading from a link ([example](http://kirkmcdonald.github.io/calc.html#zip=hY2xCsMwDET/xpM9JIEOAX2MYytF4NhCkkv7903I0AwtBXHoTo/TRhUmt3YsUHsqGCUcxi1YDPDJgqrBJFblJhaO2OUNeHJ5AT00wXBzZLgpsLTck9GD7BW2fS8YpnmdR6+MmK/R4OhemyCkxowSuERDv6sapbBE8drL2mU3MVH2JK2ekDtbfn3Tz/hvxPiPuN7f)) the ingredients are missing instantly (on load). 
When adding the products from a [empty page](http://kirkmcdonald.github.io/calc.html), the errounus results can not reliably reproduced. Maybe a problem with the new settings. 
In both cases the visual representation works as expected. 
 

I am using Chrome v64 (stable, 32bit). 
![image](https://user-images.githubusercontent.com/29695655/39366951-b00cfebc-4a35-11e8-88dd-772b736e8973.png)

Thanks for your efforts.

**Comment by Calibretto22** [comment]
Addendum: I suspect setting the default Module a Productivity Module breaks "something".

**Comment by KirkMcDonald** [comment]
Fixed in 85274382ccc4e1674c3e270e2f5a9e6e88a7035b.
