### ISSUE TITLE
FollowUp to #79: empty default module-slots prevent calculation

### ISSUE THREAD

**Issue by Calibretto22** [KirkMcDonald/kirkmcdonald.github.io#80]
When starting a new calculation - without default modules set - the production numbers are not updated after entering a number of factories. And vice versa. 

![image](https://user-images.githubusercontent.com/29695655/39394544-6c807284-4ad3-11e8-8b36-37f43d9544fe.png)
(no default modules set)

![image](https://user-images.githubusercontent.com/29695655/39394589-0a1f1c8e-4ad4-11e8-8ad4-0cc40729f5cf.png)
(default modules are set to speed1)

-------------------

When having a calculation like above and you remove the default module in settings again, the module setting-copy-buttons don't work: 
![image](https://user-images.githubusercontent.com/29695655/39394645-acdb73e6-4ad4-11e8-85e4-133031931538.png)
(no default modules set)

-------------------

However, if you have set a default module you can copy empty slots: 
![image](https://user-images.githubusercontent.com/29695655/39394704-5a72e9b2-4ad5-11e8-80ee-0bc905177ed1.png)
(default module is set to effectivity2)

I think this could be connected.

**Comment by NetzwergX** [comment]
Can cornfirm, had the exact same issue. Empty default module in settings completely breaks the calculator.

**Comment by KirkMcDonald** [comment]
I did a dumb. Fixed in d954fec0251f098fb1753271217b057956c3eb40.

**Comment by Calibretto22** [comment]
don't worry. 
this happens. 

i hope the descriptions made it easier to fix. 
thanks for this great calculator.

**Comment by NetzwergX** [comment]
Shit happens, don't worry. Thanks for the quick fix. Its a really great tool.
