### ISSUE TITLE
Incorrect Coal liquefaction with prod modules

### ISSUE THREAD

**Issue by jenyak** [KirkMcDonald/kirkmcdonald.github.io#88]
Calculation for Heavy oil in Coal liquefaction recipe is not correct because production bonus applies on difference between recipe ingredients and results.

Example 1 refinery with 1 prod module 3
Calculation for Heavy oil

expected value Heavy oil / sec 
`(35 * (1 + 0.1) − 25) / (5 / (1 − 0.15)) = 2.295 `
but now it's
`(35 − 25) * (1 + 0.1) / (5 / (1 − 0.15)) = 1.87`

https://kirkmcdonald.github.io/calc.html#tab=graph&rate=s&rp=6&cp=6&p=coal&pipe=10&items=heavy-oil:r:187/100&modules=coal-liquefaction:p3

**Comment by KirkMcDonald** [comment]
Fixed in 7ecbb31f47ef782b95dd3086b52d9e73ae56ed3d.
