### ISSUE TITLE
Issue with Coal Liquefaction and Miner productivity levels

### ISSUE THREAD

**Issue by FISHMANPET** [KirkMcDonald/kirkmcdonald.github.io#89]
I was using the calculator to determine how much coal I would need to liquefy to power 14 production beaker assemblers.  Using 20 Refineries, should consume about 40 coal/s, or one full blue belt.  Plus a little more for plastic so a bit over 1 blue belt's worth.  If I change the productivity bonus to 100, the calculator says I'll only need about 25 coal in total.  Changing the productivity bonus also changes slightly the number of refineries and chem plants (refineries went from 19.9 at 0% productivity to 19.2 at 100% productivity for example).

**Comment by KirkMcDonald** [comment]
Fixed in 8c8ec748fac928c5e2a4af4da3e03909d408566c.
