### ISSUE TITLE
Suggestion: Add a license

### ISSUE THREAD

**Issue by Bilka2** [KirkMcDonald/kirkmcdonald.github.io#95]
In the current unlicensed state, we are allowed to fork/clone and modify your code, but not allowed to use it. I'd like to clone the repository to use it as an offline calculator. Please add a license to your repository that allows users to do this. Thank you.

**Comment by KirkMcDonald** [comment]
The code is licensed under the Apache License 2.0, though I could do a better job of advertising that. I'll leave this issue open until I do.

**Comment by Bilka2** [comment]
I did not see this anywhere, thank you for the info.

**Comment by KirkMcDonald** [comment]
Done in 000a753defa7dcbd75e645b6f5a5b0cf7d3c5492.
