### ISSUE TITLE
Coal liquifaction/basic oil processing error: not showing up as recipe

### ISSUE THREAD

**Issue by L0laapk3** [KirkMcDonald/kirkmcdonald.github.io#99]
I've found that with large calculations like for example [this one](https://kirkmcdonald.github.io/calc.html#zip=fVRbbuMwDLyNvyIgj+2PCx+GlhiHqCwJFNVu9vRLp44dJ2qBwIFnxOHwYXHq3hqbulMzUtBn6mwE3/TopcO/iTFnIwwhp8hiJrgZE0fXve0bN3bp1Li+y6eGBMfc5QQWTbaEQf/15aPl9nDc73cXGi5G0F6q7KRYrFAMVXokTwJ8rZKPmDlV0WMVPcxoM2pyj7kj1vzJg2D7nk/t8c9Prmf2J9czXXc9k0+ua+ixih7uKEf7gaIgyxNkYxCO3pRA8uDV6iwpDBsYPVo9G8gaS2zLytyaEXlphY0pIRsLvX/GNi2bsYdIcJ+g9t1zBg3Lool74DUY/FJ18efCyoMltwWXt4Qq+z2+VqH7b+fjl3EYMol2X1iHVFY/WRD91vTcuHPBNX30oKVBUOhB+j0U79v9DqwtY1GNyDW6BxHk66IPTou8cdvH/fyt2wNqxq8Lria+x6M9wDBQwO3oXqFECWtufOlVBIK86Gozg36ytaAsUeWnwHVpJ2hNhmynfeJYgstmhAH+qaOa1plYaxt/PTMwBnB1qgSjE2SUGrsUozfY5Mcx+erMKGRkHUuN295x1X5ET+62IubMcTRe7wYxkZZhXRA+rxNgLOuXqlbuzHL0hcm6hF6vCfxlOf4D). No recipe shows up when selecting coal liquifaction or basic oil processing. All the recipes show, except for the coal liquifaction.

This appears to be consistently happening, I've tested this on multiple devices.

I've tried to look at the debugger to figure out whats going on, but its beyond me. It looks like it decided that coal liquifaction or basic oil processing is simply too much hassle and would much rather put zero of those and instead spawn in some heavy oil :p

**Comment by KirkMcDonald** [comment]
Fixed in 2329267d5218a3911791fef38a069f6255cffe14. It turns out it was applying productivity effects to disabled recipes in such a way that it threw all sorts of math off.
